### ISSUE TITLE
react-native-webrtc: android app crashes on connection attempt with NullPointerException

### ISSUE THREAD

**Issue by dchowitz** [dchowitz/webrtc-datachannel#5]
Test setting: mobile phone first connects to datachannel, then browser.
App crashes immediately.

```

03-09 16:17:09.439 27090 27406 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
03-09 16:17:09.450 27090 27406 W System.err: 	at org.webrtc.JniHelper.getStringBytes(JniHelper.java:25)
03-09 16:17:09.450 27090 27406 W System.err: 	at org.webrtc.PeerConnection.nativeCreateDataChannel(Native Method)
03-09 16:17:09.451 27090 27406 W System.err: 	at org.webrtc.PeerConnection.createDataChannel(PeerConnection.java:709)
03-09 16:17:09.451 27090 27406 W System.err: 	at com.oney.WebRTCModule.PeerConnectionObserver.createDataChannel(PeerConnectionObserver.java:166)
03-09 16:17:09.451 27090 27406 W System.err: 	at com.oney.WebRTCModule.WebRTCModule.createDataChannelAsync(WebRTCModule.java:918)
03-09 16:17:09.451 27090 27406 W System.err: 	at com.oney.WebRTCModule.WebRTCModule.lambda$createDataChannel$17$WebRTCModule(WebRTCModule.java:905)
03-09 16:17:09.451 27090 27406 W System.err: 	at com.oney.WebRTCModule.WebRTCModule$$Lambda$17.run(Unknown Source)
03-09 16:17:09.451 27090 27406 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-09 16:17:09.451 27090 27406 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-09 16:17:09.451 27090 27406 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-09 16:17:09.452 27090 27406 E rtc     : 
03-09 16:17:09.452 27090 27406 E rtc     : 
03-09 16:17:09.452 27090 27406 E rtc     : #
03-09 16:17:09.452 27090 27406 E rtc     : # Fatal error in gen/sdk/android/generated_base_jni/jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 38
03-09 16:17:09.452 27090 27406 E rtc     : # last system error: 11
03-09 16:17:09.452 27090 27406 E rtc     : # Check failed: !env->ExceptionCheck()
03-09 16:17:09.452 27090 27406 E rtc     : # 
03-09 16:17:09.452 27090 27406 E rtc     : #
```

**Comment by dchowitz** [comment]
This issue is probably caused by react-native-webrtc.

**Comment by dchowitz** [comment]
This error can be fixed by defensively checking for null and undefined offers/answers/candidates.

**Comment by ThumbstackTech** [comment]
Are this fixes published facing the same issue in  "react-native-webrtc": "^1.84.0",

**Comment by DaveLomber** [comment]
according to 

https://github.com/ant-media/Ant-Media-Server/issues/2670
https://github.com/ant-media/Ant-Media-Server/issues/2298 

it should be fixed in M85
